env: order-dev22
# eureka:
#   client:
#     service-url:
#         defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: order # 服务名称
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///pm208?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 9090
PRODUCT:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
