spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///pm208?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 8686
